name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: APT Cache
      uses: actions/cache@v2.0.0
      with:
        path: |
          /var/cache/apt/archives/
          ~/.m2
          ~/install_clojure.sh
        key: ${{ runner.os }}-cache

    - run: sudo apt update && sudo apt upgrade -y
    - name: install system dependencies
      run: sudo apt-get install -y gjs leiningen
    
    # Install clojure.
    - run: curl -o ~/install_clojure.sh -O https://download.clojure.org/install/linux-install-1.10.1.536.sh 
    - run: chmod +x ~/install_clojure.sh
    - run: sudo ~/install_clojure.sh
    
    - run: which clojure

    - name: Install maven dependencies
      run: lein deps
      
    - name: Run tests
      run: lein test

