name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: APT Cache
      uses: actions/cache@v2.0.0
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt

    - name: install system dependencies
      run: sudo apt-get install -y gjs leiningen clojure
      
    - name: Maven cache
      uses: actions/cache@v2.0.0
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven

    - name: Install maven dependencies
      run: lein deps
      
    - name: Run tests
      run: lein test

