name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: APT Cache
      uses: actions/cache@v2.0.0
      with:
        path: |
          /var/cache/apt/archives/
          ~/.m2
          ~/install_clojure.sh
        key: ${{ runner.os }}-cache

    - run: sudo apt update
    - name: install system dependencies
      run: sudo apt-get install -y gjs leiningen clojure
    
    - run: which clojure
    
    - run: clj -Spath

    - name: Install maven dependencies
      run: lein deps
      
    - name: Run tests
      run: lein test

